### ISSUE TITLE
Mime::PDF seems to be undefined in Rails 5.1

### ISSUE THREAD

**Issue by stephanpavlovic** [railslove/happypdf_renderer#2]
I fixed in local by replacing **type => Mime::PDF.to_s** with **Mime::EXTENSION_LOOKUP['pdf'].to_s**

**Comment by bumi** [comment]
do you have a full stack trace of this? wanna make a PR with the change? :)

**Comment by stephanpavlovic** [comment]
Stacktrace is not that much.

`Completed 500 Internal Server Error in 560ms (ActiveRecord: 1.8ms)
uninitialized constant Mime::PDF excluded from capture: DSN not set
NameError (uninitialized constant Mime::PDF):
app/controllers/donations_controller.rb:25:in `block (2 levels) in download'
app/controllers/donations_controller.rb:24:in `download'`
I could do a PR, but I'm not sure if **Mime::EXTENSION_LOOKUP['pdf']** is the correct/best way to access the string "application/pdf" and what has changed in Rails 5 so it is no longer available as Mime::PDF

**Comment by stephanpavlovic** [comment]
In _https://github.com/rails/rails/blob/fe1f4b2ad56f010a4e9b93d547d63a15953d9dc2/actionpack/test/dispatch/mime_type_test.rb_ the use **Mime[:pdf].to_s**, I do a PR with this, looks better to me, then the solution above

**Comment by bumi** [comment]
ahh, interesting find, good to know. 

but is that an issue in your rails app or in the gem? (I don't find any use of Mime::PDF here?)

**Comment by stephanpavlovic** [comment]
https://github.com/railslove/happypdf_renderer/blob/master/lib/happypdf_renderer.rb#L33

**Comment by stephanpavlovic** [comment]
https://github.com/railslove/happypdf_renderer/pull/4 Tested that this also works in a Rails 3.2 app....

**Comment by bumi** [comment]
ahhh, missed that.
